'use client'

import { Zap, Share2 } from 'lucide-react'
import { cn } from '@/lib/utils'

interface WhiteLabelFooterProps {
  merchantName: string
  referralId: string
  isPremium?: boolean
}

export function WhiteLabelFooter({ merchantName, referralId, isPremium }: WhiteLabelFooterProps) {
  return (
    <div className="mt-12 pt-8 border-t border-dashed border-border/50 flex flex-col items-center gap-6">
      {/* Merchant Branding */}
      <div className="text-center">
        <p className="text-[10px] font-black uppercase tracking-[0.2em] text-muted-foreground opacity-40">Invoice Generated By</p>
        <p className="text-sm font-black uppercase tracking-tight mt-1 text-foreground">{merchantName}</p>
      </div>

      {/* BillZo Growth Link */}
      <div className="group cursor-pointer">
        <a 
          href={`https://billzo.in/ref/${referralId}`}
          target="_blank"
          rel="noopener noreferrer"
          className="flex items-center gap-2.5 px-4 py-2 rounded-full bg-muted/30 border border-border/50 hover:bg-primary/5 hover:border-primary/20 transition-all"
        >
          <Zap className="w-3.5 h-3.5 text-primary fill-primary/20" />
          <span className="text-[9px] font-black uppercase tracking-widest text-muted-foreground group-hover:text-primary transition-colors">
            Powered by <span className="text-foreground font-black group-hover:text-primary">BillZo</span>
          </span>
          <div className="w-1.5 h-1.5 rounded-full bg-primary/20 group-hover:bg-primary animate-pulse transition-colors" />
        </a>
      </div>

      {/* QR Social Share (Optional Growth Trigger) */}
      {!isPremium && (
        <div className="p-4 bg-muted/10 rounded-2xl border border-border/30 text-center max-w-[200px]">
           <p className="text-[8px] font-bold text-muted-foreground uppercase leading-tight">
             Want faster billing for your business? Scan this bill to start.
           </p>
        </div>
      )}
    </div>
  )
}
