export { TransportRegistry } from './registry'
export type { ProviderResolver } from './registry'
export { MetaAdapter } from './meta'
export type { MetaConfigResolver } from './meta'
export { GupshupAdapter } from './gupshup'
export type { GupshupConfigResolver, GupshupChannelConfig, CircuitBreakerStore } from './gupshup'
export { BaileysAdapter } from './baileys'
export type { BaileysSocketHost, BaileysTenantResolver } from './baileys'
export { SimulationAdapter } from './simulation'
export type { TransportAdapter, OutboundMessage, SendResult, ChannelHealth, ConnectionState } from './types'
